[package]
name = "rust_crush_course"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.29.0"
polars-lazy = "0.29.0"
rand = "0.8.5"
