mod arrays;
mod cli;
mod closures;
mod conditionals;
mod enums;
mod functions;
mod if_let;
mod loops;
mod map;
mod optional_enum;
mod pointer_references;
mod polars_dataframes;
mod print;
mod rectangles_struct_example;
mod slice_type;
mod string_slices;
mod strings;
mod structs;
mod tuples;
mod types;
mod vars;
mod vectors;

fn main() {
    print::run();
    vars::run();
    types::run();
    strings::run();
    tuples::run();
    arrays::run();
    vectors::run();
    conditionals::run();
    loops::run();
    functions::run();
    pointer_references::run();
    structs::run();
    enums::run();
    cli::run();
    slice_type::run();
    string_slices::run();
    rectangles_struct_example::run();
    optional_enum::run();
    if_let::run();
    closures::run();
    map::run();
    polars_dataframes::run();
}
